{
 "title": "Volks",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Background",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<html>\n<style>\n  body {\n    background-image: url('https://img.freepik.com/free-vector/gradient-network-connection-background_23-2148879890.jpg?size=626&ext=jpg&ga=GA1.1.2113030492.1720224000&semt=ais_user');\n    background-size: cover;\n    background-repeat: no-repeat;\n    background-position: center;\n  }\n</style>\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 13, "x": 5, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Zabbix Agent Status</title>\n  <style>\n    .up {\n      color: green;\n    }\n\n    .down {\n      color: red;\n    }\n  </style>\n</head>\n\n<body>\n  <div class=\"container\">\n    <div class=\"title\">Zabbix Agent</div>\n    <div class=\"status\">\n      STATUS DO AGENT:\n      {{#each data}}\n      {{#if @last}}\n      {{#if (eq Value 1)}}\n      <span class=\"value up\">UP</span>\n      {{else}}\n      <span class=\"value down\">DOWN</span>\n      {{/if}}\n      {{/if}}\n      {{/each}}\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Zabbix agent availability" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 11 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "/received|sent/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}